"""create employees table

Revision ID: 072993d0c80b
Revises: 80b65dbee7d0
Create Date: 2026-05-24 17:04:01.088921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072993d0c80b'
down_revision: Union[str, None] = '80b65dbee7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('salary > 0', name='ck_employees_salary_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_job_title'), ['job_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_salary'), ['salary'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_status'))
        batch_op.drop_index(batch_op.f('ix_employees_salary'))
        batch_op.drop_index(batch_op.f('ix_employees_job_title'))
        batch_op.drop_index(batch_op.f('ix_employees_full_name'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_index(batch_op.f('ix_employees_department'))
        batch_op.drop_index(batch_op.f('ix_employees_country'))

    op.drop_table('employees')
    # ### end Alembic commands ###
